language: java

os: linux
dist: trusty
jdk: oraclejdk8

install:
  - TERM=dumb ./gradlew assemble

script: 
  - TERM=dumb ./gradlew check./gradlew build --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
